(ns paleodb.foods.nutrition
  (:use zolo.utils.debug
        zolo.utils.clojure))

(def FOODS {
            :beef [:meat]
            :bison [:meat]
            :boar [:meat]
            :buffalo [:meat]
            :chicken [:meat]
            :duck [:meat]
            :egsg []
            :game [:meat]
            :goat [:meat]
            :goose [:meat]
            :lamb [:meat]
            :mutton [:meat]
            :ostrich [:meat]
            :pork [:meat]
            :quail [:meat]
            :rabbit [:meat]
            :squab [:meat]
            :turkey [:meat]
            :veal [:meat]
            :venison [:meat]
            :catfish [:seafood :fish]
            :carp [:seafood :fish]
            :clams [:seafood]
            :grouper [:seafood :fish]
            :halibut [:seafood :fish]
            :herring [:seafood :fish]
            :lobster [:seafood]
            :mackerel [:seafood :fish]
            :mahi-mahi [:seafood :fish]
            :mussels [:seafood]
            :oysters [:seafood]
            :salmon [:seafood :fish]
            :sardines [:seafood :fish]
            :scallops [:seafood :fish]
            :shrimp [:seafood]
            :prawns [:seafood]
            :snails [:seafood]
            :snapper [:seafood :fish]
            :swordfish [:seafood :fish]
            :trout [:seafood :fish]
            :tuna [:seafood :fish]
            :liver [:super-food]
            :kidney [:super-food]
            :heart [:super-food]

            :seaweed [:super-food]
            :kelp [:super-food]
            :dulse [:super-food]
            :bone-broth [:super-food :home-made]

            :sauerkraut [:fermented :super-food]
            :carrots [:fermented :super-food]
            :beets [:fermented :super-food]
            :yogurt [:fermented :super-food]
            :kefir [:fermented :super-food]
            :kombucha [:fermented :super-food]
            
            :avocado-oil [:oil]
            :bacon-fat [:fat]
            :lard [:fat]
            :butter [:fat :grass-fed :super-food]
            :coconut-milk [:fat]
            :coconut-oil [:oil]
            :duck-fat [:fat]
            :ghee [:fat :grass-fed :super-food]
            :macadamia-oil [:oil]
            :olive-oil [:oil]
            :palm-oil [:oil]
            :schmaltz [:fat]
            :sesame-oil [:oil]
            :suet [:oil]
            :tallow [:fat]
            :walnut-oil [:oil]

            :almonds []
            :brazil-nuts []
            :chestnuts []
            :hazelnuts []
            :macadamia-nuts []
            :pecans []
            :pine-nuts []
            :pistachios [:fodmap ]
            :pumpkin-seeds []
            :sesame-seeds []
            :sunflower-seeds []
            :walnuts []

            :almond-milk []
            :coconut-water []
            :herbal-tea []
            :mineral-water []
            :water []

            })

(def BAD [:fodmap :phytates :gluten])

(def fodmap "FODMAPs are short chain carbohydrates and monosaccharides that are poorly absorbed in the small intestine, including fructans, galactans, fructose and polyols. The term is an acronym, deriving from 'Fermentable, Oligo-, Di-, Mono-saccharides And Polyols'. The restriction of FODMAPs from the diet has been found to have a beneficial effect for sufferers of irritable bowel syndrome and other functional gut disorders. The low FODMAP diet was developed at Monash University in Melbourne.")